name: Build BTC Price & Publish

on:
  schedule:
    - cron: "*/10 * * * *"   # a cada 10 min (UTC)
  workflow_dispatch:

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-price:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests==2.32.3

      # garante que news.json estará presente no deploy
      - name: Fetch latest news.json (carry-over)
        run: |
          mkdir -p public
          curl -fsSL https://guibim.github.io/btcheck/news.json -o public/news.json \
            || echo "[]" > public/news.json

      - name: Build BTC price (USD+BRL)
        run: python scripts/get_btc_price.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
