name: Build BTC Price & Publish

on:
  schedule:
    - cron: "*/10 * * * *"   # a cada 10 minutos (UTC)
  workflow_dispatch:

jobs:
  build-price:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    env:
      TZ: America/Sao_Paulo
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests==2.32.3

      - name: Build BTC price (USD+BRL)
        run: python scripts/get_btc_price.py

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - uses: actions/deploy-pages@v4
