name: Build news.json & Publish

on:
  schedule:
    - cron: "10 12 * * *"   # 09:10 BRT
    - cron: "10 22 * * *"   # 19:10 BRT
  workflow_dispatch:

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    env:
      TZ: America/Sao_Paulo
      NEWS_LIMIT: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install psycopg[binary]==3.2.1 requests==2.32.3

      - name: Build news.json
        env:
          DATABASE_URL_READONLY: ${{ secrets.DATABASE_URL_READONLY }}
          NEWS_LIMIT: ${{ env.NEWS_LIMIT }}
        run: python scripts/build_json.py

      # garante que btc_price.json estará presente no deploy
      - name: Fetch latest btc_price.json (carry-over)
        run: |
          mkdir -p public
          curl -fsSL https://guibim.github.io/btcheck/btc_price.json -o public/btc_price.json \
            || echo '{"updated_at":"","source":"coingecko","prices":{"BTC_USD":0,"BTC_BRL":0}}' > public/btc_price.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
